---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Ensure ssh is present in Arch distros
      pacman:
        name: openssh
        state: present
      become: true
      when: ansible_os_family == 'Archlinux'

    - name: Ensure ssh is present in Ubuntu distros
      apt:
        name: openssh-server
        state: present
      become: true
      when: ansible_distribution == 'Ubuntu'
